#### Good Job, `Promise`

While inside `Promise` and outside its `resolve` firstly returns the stuff, the stuff inside the `resolve` was returned asynchronously.



```javascript
var Pro = function (time) {
    //返回一个Promise对象
    return new Promise(function (resolve, reject) {
        console.log('123'); // 2.1, 3.1
        //模拟接口调用
        setTimeout(function () {
            //这里告诉Promise 成功了，然后去执行then方法的第一个函数
            // in "then", it returns the "resolve"
            resolve('成功返回'); // 2.2 (3s后), 3.2 ((3 + 5)s后)
        }, time);
    })
};
(
    function(){
    console.log('start'); // 1
    Pro(3000) // 2
    .then(function(data)
        {
        console.log(data); // 2.3
        return Pro(5000); // 3
    })
    .then(function(data)
    {
        console.log(data); // 3.3
        console.log('end'); // 3.4
    })
}
)();

// returns as:
/*
start
123
成功返回
123
成功返回
end
*/

```

